name: React Native CI Git Action

env:
  main_project_module: ReactNativeCI

on:
  push:

jobs:
  builds:
     runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Set current date as env variable
          run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

        - name: Set repository name as env variable
          run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

        - name: SetUp JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '21'

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
        
        - name: Install dependencies
          run: yarn install

        - name: Setup Android SDK
          uses: android-actions/setup-android@v3

        - name: Build Android APK
          run: |
            cd android
            chmod 0755 gradlew
            ./gradlew assembleRelease

        - name: Build Android AAB
          run: |
            cd android
            chmod 0755 gradlew
            ./gradlew bundleRelease

         - name: Upload APK Release - ${{ env.repository_name }}
           uses: actions/upload-artifact@v4
           with:
             name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) release generated
             path: android/app/build/outputs/apk/release/

         - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
           uses: actions/upload-artifact@v4
           with:
             name: ${{ env.date_today }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
             path: android/app/build/outputs/bundle/release/

